const fs = require('fs');
const { EmbedBuilder, ActionRowBuilder, ButtonBuilder, ButtonStyle } = require('discord.js');

module.exports = async (msg) => {
    if (msg.content !== '!job') return false;

            const embed = new EmbedBuilder()
                            .setTitle('🦢 | 鵝鵝職業中心')
                                                    .setColor('#0099FF')
                                                                                    .setDescription('請選擇一個你想從事的職業：\n\n⛏️ **礦工**: 採集礦石與寶石\n🎣 **漁夫**: 捕捉各種淡水魚\n👨‍🌾 **牧農**: 飼養與照顧動物\n🪓 **伐木工**: 砍伐木材資源\n🌾 **農夫**: 種植與收穫作物')
                                                                                                                            .setFooter({ text: '注意：選擇新職業可能會覆蓋舊職業！' });

                                                                                                                                                                      const row = new ActionRowBuilder().addComponents(
    new ButtonBuilder().setCustomId('job_miner').setLabel('礦工').setStyle(ButtonStyle.Primary).setEmoji('⛏️'),
    new ButtonBuilder().setCustomId('job_fisher').setLabel('漁夫').setStyle(ButtonStyle.Primary).setEmoji('🎣'),
    new ButtonBuilder().setCustomId('job_rancher').setLabel('牧農').setStyle(ButtonStyle.Primary).setEmoji('🐂'),
    new ButtonBuilder().setCustomId('job_woodcutter').setLabel('伐木工').setStyle(ButtonStyle.Primary).setEmoji('🪓'),
    new ButtonBuilder().setCustomId('job_farmer').setLabel('農夫').setStyle(ButtonStyle.Primary).setEmoji('🧑‍🌾')
);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                await msg.reply({ embeds: [embed], components: [row] });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return true;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                